force-app/main/default/objects/TV_Show__c/TV_Show__c.object-meta.xml
<CustomObject>
    <label>TV Show</label>
    <nameField>
        <label>TV Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Shows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TV_Show__c/fields/Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Logo_URL__c</fullName>
    <label>Logo URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/ShowController.cls
public with sharing class ShowController {
    @AuraEnabled(Cacheable=true)
    public static TV_Show__c[] getShowById(String showId) {
        return [
            SELECT
                Id,
                Name,
                Description__c,
                Logo_URL__c
            FROM TV_Show__c
            WHERE Id = :showId
        ];
    }

    @AuraEnabled(Cacheable=true)
    public static TV_Show__c[] getAllShows() {
        return [
            SELECT
                Id,
                Name,
                Description__c,
                Logo_URL__c
            FROM TV_Show__c
            ORDER BY Name
            LIMIT 50
        ];
    }

    @AuraEnabled(Cacheable=true)
    public static TV_Show__c[] searchShows(String searchTerm) {
        searchTerm = searchTerm.trim();
        if (searchTerm == '') {
            return getAllShows();
        }
        // Prepare query paramters
        searchTerm = '%' + searchTerm + '%';
        // Execute search query
        return [
            SELECT
                Id,
                Name,
                Description__c,
                Logo_URL__c
            FROM TV_Show__c
            WHERE Name LIKE :searchTerm
            ORDER BY Name
            LIMIT 50
        ];
    }
}