force-app/main/default/objects/Episode__c/fields/TV_Show__c.field-meta.xml
<CustomField>
    <fullName>TV_Show__c</fullName>
    <label>TV Show</label>
    <referenceTo>TV_Show__c</referenceTo>
    <relationshipLabel>All Episodes</relationshipLabel>
    <relationshipName>Episodes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <displayFormat>S{00}</displayFormat>
        <label>Season Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TV_Show__c/TV_Show__c.object-meta.xml
<CustomObject>
    <label>TV Show</label>
    <nameField>
        <label>TV Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Shows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SeasonController.cls
public with sharing class SeasonController {
    @AuraEnabled(Cacheable=true)
    public static Season__c[] getSeasonByShowId(String showId) {
        return [
            SELECT
                Id,
                Number__c,
                Description__c,
                (SELECT Id, Name FROM Episodes__r)
            FROM Season__c
            WHERE TV_Show__c = :showId
            ORDER BY Number__c ASC
        ];
    }

}